seed: 0
data_folder: !PLACEHOLDER
hpopt_mode: orion
hpopt: hpopt.yaml
ckpt_enable: True
batch_size: 32
number_of_epochs: 20
#--------------------------------- hparams ------------------------------------
annot_value: 2
dropout: 0.2
#---------------------------------- Classes -----------------------------------
Prolongation: False
Block: False
SoundRep: False
WordRep: False
Interjection: True
num_class: !!python/object/apply:eval [ !ref <Prolongation> + <Block> + <SoundRep> + <WordRep> + <Interjection>]
#----------------------------------- Feats ------------------------------------
remove_unsure: False
#----------------------------------- Loss -------------------------------------
positive: 1
loss: !new:torch.nn.CrossEntropyLoss
#----------------------------------- Model ------------------------------------
wav2vec2: !new:speechbrain.lobes.models.huggingface_transformers.wav2vec2.Wav2Vec2
    source: facebook/wav2vec2-base-960h
    save_path: !ref <data_folder>/pretrained_model
    freeze_feature_extractor: True
    freeze: True
size_i: 114432
size_h: 1024
layer1: !new:torch.nn.Linear
    in_features: !ref <size_i>
    out_features: !ref <size_h>

layer2: !new:torch.nn.Linear
    in_features: !ref <size_h>
    out_features: 1

bn1: !new:speechbrain.nnet.normalization.BatchNorm1d
    input_size: !ref <size_i>
    
bn2: !new:speechbrain.nnet.normalization.BatchNorm1d
    input_size: !ref <size_h>

do: !new:torch.nn.Dropout
    p: !ref <dropout>

model: !new:torch.nn.Sequential
  - !ref <wav2vec2>
  - !new:torch.nn.Flatten  
  - !ref <bn1>
  - !ref <do>
  - !ref <layer1>
  - !new:torch.nn.LeakyReLU
  - !ref <bn2>
  - !ref <do>
  - !ref <layer2>

    
#-------------------------------- Scheduling ----------------------------------
dataloader_opts:
    batch_size: !ref <batch_size>
    shuffle: True

learning_rate: 0.00004
opt_class: !name:torch.optim.AdamW
    lr: !ref <learning_rate>

#---------------------------------- Misc --------------------------------------
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/<seed>

counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

modules:
    model: !ref <model>

save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        counter: !ref <counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
