# ############################################################################
# Model: K-means
# Training: LJSpeech
# Authors:  Duret, Jarod 2023
# ############################################################################


###################################
# Experiment Parameters and setup #
###################################
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]
no_cuda: False
output_folder: !ref ./results/kmeans/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

#################################
# Data files and pre-processing #
#################################
data_folder: !PLACEHOLDER
train_json: !ref <save_folder>/train.json
valid_json: !ref <save_folder>/valid.json
splits: [train, valid]
split_ratio: [90, 10]
skip_prep: False

# URL for the HuggingFace model we want to load
encoder_hub: voidful/mhubert-base #!PLACEHOLDER

# Features arguments
layer: 11 #!PLACEHOLDER
sample_pct: 0.2

####################
# Model Parameters #
####################
num_clusters: 1000
init: k-means++
max_iter: 100
batch_size: 10000
tol: 0.0
max_no_improvement: 100
n_init: 20
reassignment_ratio: 0.0
out_kmeans_model_path: !ref <output_folder>/kmeans.cpt



