# ############################################################################
# S2U: Train Kmeans to extract discrete units for HiFi-GAN
# Training: LJSpeech
# Authors:  Duret, Jarod 2022
# ############################################################################


###################################
# Experiment Parameters and setup #
###################################
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]
no_cuda: False
output_folder: !PLACEHOLDER #!ref ../results/hifi_gan/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt


#################################
# Data files and pre-processing #
#################################
data_folder: !PLACEHOLDER # e.g, /datasets/ljspeech
train_json: !ref <save_folder>/train.json
valid_json: !ref <save_folder>/valid.json
splits: [train, valid]
split_ratio: [90, 10]
skip_prep: False
embedding_type: !PLACEHOLDER

# Features arguments
feats_folder: !PLACEHOLDER
sample_pct: 0.2

# K-means arguments
num_clusters: 100
init: k-means++
max_iter: 100
batch_size: 10000
tol: 0.0
max_no_improvement: 100
n_init: 20
reassignment_ratio: 0.0
out_kmeans_model_path: !ref <save_folder>/kmeans.cpt



